### ISSUE TITLE
Empty cells cause misleading guesses

### ISSUE THREAD

**Issue by danfowler** [sballesteros/jts-infer#3]
Hello, thanks for this library :).  I've noticed some strange inferences when using jts-infer on tables with empty fields.  For example:

```
a,b,c
20,20,20
20,20,20
20,20,20
```

becomes

```
{ fields: 
   [ { name: 'a', type: 'integer' },
     { name: 'b', type: 'integer' },
     { name: 'c', type: 'integer' } ] }
```

while

```
a,b,c
20,20,20
20,,20
20,20,20
```

becomes

```
{ fields: 
   [ { name: 'a', type: 'integer' },
     { name: 'b', type: 'number' },
     { name: 'c', type: 'integer' } ] }
```

I wonder: should empty cells be skipped in the scoring algorithm?

**Comment by sballesteros** [comment]
Thanks for reporting!
Sorry I should have updated the README but I have stopped maintaining this lib and instead have been working on 
https://github.com/scienceai/preview-tabular-data which does the same thing but use the [Metadata Vocabulary for Tabular Data](http://www.w3.org/TR/tabular-metadata/) to describe the columns.
The inference itself is done by https://github.com/scienceai/jsonld-context-infer.

I will have a look there and we can fix it there.

**Comment by danfowler** [comment]
Thanks for your quick response :).  Cheers :+1:

**Comment by sballesteros** [comment]
ok this is fixed by https://github.com/scienceai/jsonld-context-infer/commit/d2ab699a1f3c5eade0543de43ccdef0df7b16d9a and https://github.com/scienceai/preview-tabular-data/commit/1b6da82b6e65187019598089c6d62dbc5bb2558f taking your suggestion to skip empty cells from the scoring algo
